// SERVE OS Template Definitions
// These templates define the fillable forms for creating artifacts

import type { SensitivityTier } from '@/types/database'

export interface TemplateField {
  id: string
  name: string
  label: string
  type: 'text' | 'textarea' | 'number' | 'date' | 'select' | 'multiselect' | 'checkbox' | 'rich_text'
  required: boolean
  options?: string[]
  placeholder?: string
  helpText?: string
  section?: string
}

export interface Template {
  id: string
  code: string
  name: string
  description: string
  category: 'intake' | 'discovery' | 'delivery' | 'governance'
  sensitivityTier: SensitivityTier
  fields: TemplateField[]
}

export const TEMPLATES: Template[] = [
  {
    id: 'TPL-01',
    code: 'TPL-01',
    name: 'Client Discovery Brief',
    description: 'Initial client information capture to understand the business context and AI readiness.',
    category: 'intake',
    sensitivityTier: 'T1',
    fields: [
      {
        id: 'company_overview',
        name: 'company_overview',
        label: 'Company Overview',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the company, its industry, size, and core business...',
        helpText: 'Provide a brief overview of the client organization',
        section: 'Company Information',
      },
      {
        id: 'primary_objectives',
        name: 'primary_objectives',
        label: 'Primary Objectives',
        type: 'textarea',
        required: true,
        placeholder: 'What does the client hope to achieve with AI implementation?',
        helpText: 'List the main goals and expected outcomes',
        section: 'Company Information',
      },
      {
        id: 'current_challenges',
        name: 'current_challenges',
        label: 'Current Challenges',
        type: 'textarea',
        required: true,
        placeholder: 'What pain points or inefficiencies is the client experiencing?',
        helpText: 'Describe the problems that need to be solved',
        section: 'Current State',
      },
      {
        id: 'existing_tech_stack',
        name: 'existing_tech_stack',
        label: 'Existing Technology Stack',
        type: 'textarea',
        required: false,
        placeholder: 'List current tools, platforms, and systems in use...',
        helpText: 'Include CRM, ERP, communication tools, databases, etc.',
        section: 'Current State',
      },
      {
        id: 'data_availability',
        name: 'data_availability',
        label: 'Data Availability',
        type: 'select',
        required: true,
        options: ['Extensive data available', 'Some data available', 'Limited data', 'No structured data'],
        helpText: 'Assess the quality and quantity of available data',
        section: 'Current State',
      },
      {
        id: 'budget_range',
        name: 'budget_range',
        label: 'Budget Range',
        type: 'select',
        required: false,
        options: ['Under $10K', '$10K - $25K', '$25K - $50K', '$50K - $100K', 'Over $100K', 'Not disclosed'],
        helpText: 'Approximate budget for AI implementation',
        section: 'Project Parameters',
      },
      {
        id: 'timeline_expectations',
        name: 'timeline_expectations',
        label: 'Timeline Expectations',
        type: 'select',
        required: true,
        options: ['Immediate (< 1 month)', 'Short-term (1-3 months)', 'Medium-term (3-6 months)', 'Long-term (6+ months)'],
        helpText: 'Expected timeframe for implementation',
        section: 'Project Parameters',
      },
      {
        id: 'key_stakeholders',
        name: 'key_stakeholders',
        label: 'Key Stakeholders',
        type: 'textarea',
        required: true,
        placeholder: 'List decision makers and key contacts with their roles...',
        helpText: 'Include name, title, and level of involvement',
        section: 'Project Parameters',
      },
      {
        id: 'success_criteria',
        name: 'success_criteria',
        label: 'Success Criteria',
        type: 'textarea',
        required: true,
        placeholder: 'How will success be measured?',
        helpText: 'Define specific, measurable outcomes',
        section: 'Project Parameters',
      },
      {
        id: 'notes',
        name: 'notes',
        label: 'Additional Notes',
        type: 'textarea',
        required: false,
        placeholder: 'Any other relevant information...',
        section: 'Additional Information',
      },
    ],
  },
  {
    id: 'TPL-02',
    code: 'TPL-02',
    name: 'Current State Map',
    description: 'Document existing processes, workflows, and pain points.',
    category: 'discovery',
    sensitivityTier: 'T1',
    fields: [
      {
        id: 'process_name',
        name: 'process_name',
        label: 'Process Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., Customer Onboarding, Invoice Processing',
        section: 'Process Overview',
      },
      {
        id: 'process_owner',
        name: 'process_owner',
        label: 'Process Owner',
        type: 'text',
        required: true,
        placeholder: 'Name and role of the person responsible',
        section: 'Process Overview',
      },
      {
        id: 'process_description',
        name: 'process_description',
        label: 'Process Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the current process step by step...',
        section: 'Process Overview',
      },
      {
        id: 'frequency',
        name: 'frequency',
        label: 'Process Frequency',
        type: 'select',
        required: true,
        options: ['Multiple times daily', 'Daily', 'Weekly', 'Monthly', 'Quarterly', 'Ad-hoc'],
        section: 'Process Metrics',
      },
      {
        id: 'time_per_instance',
        name: 'time_per_instance',
        label: 'Time Per Instance (minutes)',
        type: 'number',
        required: true,
        placeholder: 'Average time to complete one instance',
        section: 'Process Metrics',
      },
      {
        id: 'volume',
        name: 'volume',
        label: 'Monthly Volume',
        type: 'number',
        required: false,
        placeholder: 'Approximate number of instances per month',
        section: 'Process Metrics',
      },
      {
        id: 'pain_points',
        name: 'pain_points',
        label: 'Pain Points',
        type: 'textarea',
        required: true,
        placeholder: 'What are the main issues with this process?',
        section: 'Analysis',
      },
      {
        id: 'tools_used',
        name: 'tools_used',
        label: 'Tools Used',
        type: 'textarea',
        required: false,
        placeholder: 'List all tools and systems involved...',
        section: 'Analysis',
      },
      {
        id: 'automation_potential',
        name: 'automation_potential',
        label: 'Automation Potential',
        type: 'select',
        required: true,
        options: ['High - Fully automatable', 'Medium - Partially automatable', 'Low - Requires human judgment'],
        section: 'Analysis',
      },
    ],
  },
  {
    id: 'TPL-03',
    code: 'TPL-03',
    name: 'Future State Design',
    description: 'Define target automation state and AI-enhanced workflows.',
    category: 'delivery',
    sensitivityTier: 'T2',
    fields: [
      {
        id: 'solution_name',
        name: 'solution_name',
        label: 'Solution Name',
        type: 'text',
        required: true,
        placeholder: 'Name for the proposed solution',
        section: 'Solution Overview',
      },
      {
        id: 'target_process',
        name: 'target_process',
        label: 'Target Process',
        type: 'text',
        required: true,
        placeholder: 'Which process will be transformed?',
        section: 'Solution Overview',
      },
      {
        id: 'ai_components',
        name: 'ai_components',
        label: 'AI Components',
        type: 'multiselect',
        required: true,
        options: ['Natural Language Processing', 'Document Analysis', 'Workflow Automation', 'Data Classification', 'Predictive Analytics', 'Chatbot/Virtual Assistant', 'Content Generation', 'Decision Support'],
        section: 'Solution Overview',
      },
      {
        id: 'future_workflow',
        name: 'future_workflow',
        label: 'Future State Workflow',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the transformed process step by step...',
        section: 'Design Details',
      },
      {
        id: 'automation_percentage',
        name: 'automation_percentage',
        label: 'Expected Automation Level (%)',
        type: 'number',
        required: true,
        placeholder: 'Percentage of process that will be automated',
        section: 'Design Details',
      },
      {
        id: 'human_touchpoints',
        name: 'human_touchpoints',
        label: 'Human Touchpoints',
        type: 'textarea',
        required: true,
        placeholder: 'Where will human oversight/approval still be required?',
        section: 'Design Details',
      },
      {
        id: 'integration_requirements',
        name: 'integration_requirements',
        label: 'Integration Requirements',
        type: 'textarea',
        required: false,
        placeholder: 'What systems need to be integrated?',
        section: 'Technical Requirements',
      },
      {
        id: 'data_requirements',
        name: 'data_requirements',
        label: 'Data Requirements',
        type: 'textarea',
        required: true,
        placeholder: 'What data is needed to power the AI solution?',
        section: 'Technical Requirements',
      },
      {
        id: 'success_metrics',
        name: 'success_metrics',
        label: 'Success Metrics',
        type: 'textarea',
        required: true,
        placeholder: 'How will we measure success? (time saved, error reduction, etc.)',
        section: 'Outcomes',
      },
    ],
  },
  {
    id: 'TPL-05',
    code: 'TPL-05',
    name: 'Implementation Plan',
    description: 'Step-by-step implementation roadmap with milestones.',
    category: 'delivery',
    sensitivityTier: 'T2',
    fields: [
      {
        id: 'project_name',
        name: 'project_name',
        label: 'Project Name',
        type: 'text',
        required: true,
        section: 'Project Overview',
      },
      {
        id: 'project_duration',
        name: 'project_duration',
        label: 'Total Duration (weeks)',
        type: 'number',
        required: true,
        section: 'Project Overview',
      },
      {
        id: 'phase_1_tasks',
        name: 'phase_1_tasks',
        label: 'Phase 1: Setup & Configuration',
        type: 'textarea',
        required: true,
        placeholder: 'List tasks for initial setup phase...',
        section: 'Implementation Phases',
      },
      {
        id: 'phase_1_duration',
        name: 'phase_1_duration',
        label: 'Phase 1 Duration (days)',
        type: 'number',
        required: true,
        section: 'Implementation Phases',
      },
      {
        id: 'phase_2_tasks',
        name: 'phase_2_tasks',
        label: 'Phase 2: Development & Integration',
        type: 'textarea',
        required: true,
        placeholder: 'List tasks for development phase...',
        section: 'Implementation Phases',
      },
      {
        id: 'phase_2_duration',
        name: 'phase_2_duration',
        label: 'Phase 2 Duration (days)',
        type: 'number',
        required: true,
        section: 'Implementation Phases',
      },
      {
        id: 'phase_3_tasks',
        name: 'phase_3_tasks',
        label: 'Phase 3: Testing & Refinement',
        type: 'textarea',
        required: true,
        placeholder: 'List tasks for testing phase...',
        section: 'Implementation Phases',
      },
      {
        id: 'phase_3_duration',
        name: 'phase_3_duration',
        label: 'Phase 3 Duration (days)',
        type: 'number',
        required: true,
        section: 'Implementation Phases',
      },
      {
        id: 'dependencies',
        name: 'dependencies',
        label: 'Key Dependencies',
        type: 'textarea',
        required: false,
        placeholder: 'What needs to happen before work can begin?',
        section: 'Dependencies & Risks',
      },
      {
        id: 'risks',
        name: 'risks',
        label: 'Implementation Risks',
        type: 'textarea',
        required: false,
        placeholder: 'What could go wrong and how will we mitigate?',
        section: 'Dependencies & Risks',
      },
    ],
  },
  {
    id: 'TPL-09',
    code: 'TPL-09',
    name: 'ROI Calculator',
    description: 'Quantify the value and return on investment of AI implementation.',
    category: 'delivery',
    sensitivityTier: 'T2',
    fields: [
      {
        id: 'process_name',
        name: 'process_name',
        label: 'Process Being Automated',
        type: 'text',
        required: true,
        section: 'Baseline Metrics',
      },
      {
        id: 'current_hours_per_week',
        name: 'current_hours_per_week',
        label: 'Current Hours Per Week',
        type: 'number',
        required: true,
        placeholder: 'Hours spent on this process weekly',
        section: 'Baseline Metrics',
      },
      {
        id: 'hourly_cost',
        name: 'hourly_cost',
        label: 'Average Hourly Cost ($)',
        type: 'number',
        required: true,
        placeholder: 'Fully loaded cost per hour',
        section: 'Baseline Metrics',
      },
      {
        id: 'error_rate',
        name: 'error_rate',
        label: 'Current Error Rate (%)',
        type: 'number',
        required: false,
        placeholder: 'Percentage of errors/rework',
        section: 'Baseline Metrics',
      },
      {
        id: 'automation_level',
        name: 'automation_level',
        label: 'Expected Automation Level (%)',
        type: 'number',
        required: true,
        placeholder: 'Percentage of work that will be automated',
        section: 'Projected Improvements',
      },
      {
        id: 'implementation_cost',
        name: 'implementation_cost',
        label: 'Implementation Cost ($)',
        type: 'number',
        required: true,
        placeholder: 'One-time implementation cost',
        section: 'Investment',
      },
      {
        id: 'monthly_cost',
        name: 'monthly_cost',
        label: 'Monthly Operating Cost ($)',
        type: 'number',
        required: true,
        placeholder: 'Ongoing monthly cost for AI tools/maintenance',
        section: 'Investment',
      },
      {
        id: 'qualitative_benefits',
        name: 'qualitative_benefits',
        label: 'Qualitative Benefits',
        type: 'textarea',
        required: false,
        placeholder: 'Non-quantifiable benefits (employee satisfaction, faster decisions, etc.)',
        section: 'Additional Value',
      },
    ],
  },
  {
    id: 'TPL-10',
    code: 'TPL-10',
    name: 'Client Handoff',
    description: 'Final deliverable package for client with all documentation and next steps.',
    category: 'delivery',
    sensitivityTier: 'T2',
    fields: [
      {
        id: 'project_summary',
        name: 'project_summary',
        label: 'Project Summary',
        type: 'textarea',
        required: true,
        placeholder: 'High-level summary of what was delivered...',
        section: 'Executive Summary',
      },
      {
        id: 'deliverables',
        name: 'deliverables',
        label: 'Deliverables Completed',
        type: 'textarea',
        required: true,
        placeholder: 'List all deliverables with descriptions...',
        section: 'Executive Summary',
      },
      {
        id: 'outcomes_achieved',
        name: 'outcomes_achieved',
        label: 'Outcomes Achieved',
        type: 'textarea',
        required: true,
        placeholder: 'What results were achieved? Include metrics...',
        section: 'Results',
      },
      {
        id: 'training_provided',
        name: 'training_provided',
        label: 'Training Provided',
        type: 'textarea',
        required: false,
        placeholder: 'What training was delivered to the client team?',
        section: 'Knowledge Transfer',
      },
      {
        id: 'documentation_links',
        name: 'documentation_links',
        label: 'Documentation Links',
        type: 'textarea',
        required: false,
        placeholder: 'Links to user guides, SOPs, etc.',
        section: 'Knowledge Transfer',
      },
      {
        id: 'next_steps',
        name: 'next_steps',
        label: 'Recommended Next Steps',
        type: 'textarea',
        required: true,
        placeholder: 'What should the client do next?',
        section: 'Future Recommendations',
      },
      {
        id: 'expansion_opportunities',
        name: 'expansion_opportunities',
        label: 'Expansion Opportunities',
        type: 'textarea',
        required: false,
        placeholder: 'Additional areas where AI could add value...',
        section: 'Future Recommendations',
      },
    ],
  },
  {
    id: 'TPL-12',
    code: 'TPL-12',
    name: 'Case Study',
    description: 'Marketing-ready success story for portfolio.',
    category: 'delivery',
    sensitivityTier: 'T2',
    fields: [
      {
        id: 'client_name',
        name: 'client_name',
        label: 'Client Name (or Anonymous)',
        type: 'text',
        required: true,
        placeholder: 'Company name or "Leading [Industry] Company"',
        section: 'Header',
      },
      {
        id: 'industry',
        name: 'industry',
        label: 'Industry',
        type: 'text',
        required: true,
        section: 'Header',
      },
      {
        id: 'headline',
        name: 'headline',
        label: 'Headline',
        type: 'text',
        required: true,
        placeholder: 'Compelling one-line summary of the success',
        section: 'Header',
      },
      {
        id: 'challenge',
        name: 'challenge',
        label: 'The Challenge',
        type: 'textarea',
        required: true,
        placeholder: 'What problem did the client face?',
        section: 'Story',
      },
      {
        id: 'solution',
        name: 'solution',
        label: 'The Solution',
        type: 'textarea',
        required: true,
        placeholder: 'What AI solution was implemented?',
        section: 'Story',
      },
      {
        id: 'results',
        name: 'results',
        label: 'The Results',
        type: 'textarea',
        required: true,
        placeholder: 'What measurable outcomes were achieved?',
        section: 'Story',
      },
      {
        id: 'key_metrics',
        name: 'key_metrics',
        label: 'Key Metrics',
        type: 'textarea',
        required: true,
        placeholder: '3-5 compelling statistics (e.g., 50% time savings, 90% accuracy)',
        section: 'Highlights',
      },
      {
        id: 'testimonial',
        name: 'testimonial',
        label: 'Client Testimonial',
        type: 'textarea',
        required: false,
        placeholder: 'Quote from the client about the experience...',
        section: 'Highlights',
      },
      {
        id: 'approved_for_public',
        name: 'approved_for_public',
        label: 'Approved for Public Use',
        type: 'checkbox',
        required: true,
        helpText: 'Check if client has approved this for marketing use',
        section: 'Approval',
      },
    ],
  },
]

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id || t.code === id)
}

export function getTemplatesByCategory(category: Template['category']): Template[] {
  return TEMPLATES.filter((t) => t.category === category)
}
